issues:
  category:
    - sys_nav2
    - sys_wireless_station
    - sys_teleop
    - sys_other
    - sys_cicd
  type:
    - type_feature
    - type_bug
    - type_enhancement
    - type_hotfix
    - type_enhancement_tracebacks
  priority:
    - PRIORITY_LOW
    - PRIORITY_MEDIUM
    - PRIORITY_HIGH
    - PRIORITY_SATANIC
  departments:
    - by_AI
    - by_HW
    - by_IT
    - by_DATA
    - by_MTO
    - by_OPS
    - by_SD
    - by_OTHERS
prs:
  priority:
    - PRIORITY_LOW
    - PRIORITY_MEDIUM
    - PRIORITY_HIGH
    - PRIORITY_SATANIC
  category:
    - sys_nav2
    - sys_wireless_station
    - sys_teleop
    - sys_other
    - sys_cicd
  documentation:
    - doc_done
    - doc_no_req
    - doc_req
  status:
    - state_ready_to_test
    - state_testing
    - state_tech_check
    - state_qa_check
    - state_in_progress
  rejection:
    - Rejected_Checks
    - Rejected_Traceback
    - Rejected_Unforeseen
  type:
    - type_release
    - type_hotfix
