issues:
  category:
    - syst_nav2
    - syst_wireless_station
    - syst_teleoperation
    - syst_other
  type:
    - #type_feature
    - #type_bug
    - #type_enhancement
  priority:
    - PRIORITY_LOW
    - PRIORITY_MEDIUM
    - PRIORITY_HIGH
    - PRIORITY_SATANIC
  departments:
    - by_AI
    - by_HW
    - by_IT
    - by_DATA
    - by_MTO
    - by_OPS
    - by_SD
    - by_OTHERS
prs:
  priority:
    - PRIORITY_LOW
    - PRIORITY_MEDIUM
    - PRIORITY_HIGH
    - PRIORITY_SATANIC
  documentation:
    - doc_done
    - doc_no_req
    - doc_req
  status:
    - state_ready_to_test
    - state_testing
    - state_tech_check
    - state_qa_check
    - state_in_progress
  rejection:
    - Reject_Checks
    - Reject_Traceback
    - Reject_Unforeseen