issues:
  category:
    - nav2
    - wireless_station
    - teleoperation
  type:
    - feature
    - bug
    - enhancement
  priority:
    - PRIORITY_LOW
    - PRIORITY_MEDIUM
    - PRIORITY_HIGH
    - SATANIC
  departments:
    - AI
    - HW
    - IT
    - DATA
    - MTO
    - OPS
    - SD
    - OTHERS

prs:
  priority:
    - PRIORITY_LOW
    - PRIORITY_MEDIUM
    - PRIORITY_HIGH
    - SATANIC
  documentation:
    - doc_done
    - doc_no_req
    - doc_req
  status:
    - ready_to_test
    - testing
    - tech_check
    - qa_check
    - in_progress
    - stale
  rejection:
    - Rejected_Checks
    - Rejected_Traceback
    - Rejected_Unforeseen