issues:
  type:
    - feature
    - bug
    - enhancement
    - nav2
    - wireless_station
  priority:
    - PRIORITY_LOW
    - PRIORITY_MEDIUM
    - PRIORITY_HIGH
    - SATANIC
  documentation:
    - doc_no-req
    - doc_done
prs:
  priority:
    - PRIORITY_LOW
    - PRIORITY_MEDIUM
    - PRIORITY_HIGH
    - SATANIC
  documentation:
    - doc_done
    - doc_no_req
    - doc_req
  status:
    - ready_to_test
    - testing
    - tech_check
    - qa_check
    - in_progress
  rejection:
    - Rejected_Checks
    - Rejected_Traceback
    - Rejected_Unforeseen