priority_scores:
  PRIORITY_LOW: 
    weight: 1
    color: "#FFFF00"
  PRIORITY_MEDIUM:
    weight: 2
    color: "#FFA500"
  PRIORITY_HIGH: 
    weight: 3
    color: "#F35325"
  PRIORITY_SATANIC: 
    weight: 5
    color: "#8B0000"
  UNCATEGORIZED: 
    weight: 0
    color: "#A9A9A9"